#pragma once
#include "ywx/core.h"

namespace yw {

enum class input {
  lbutton = VK_LBUTTON,
  rbutton = VK_RBUTTON,
  mbutton = VK_MBUTTON,
  xbutton1 = VK_XBUTTON1,
  xbutton2 = VK_XBUTTON2,

  backspace = VK_BACK,
  tab = VK_TAB,
  enter = VK_RETURN,
  shift = VK_SHIFT,
  ctrl = VK_CONTROL,
  alt = VK_MENU,
  caps_lock = VK_CAPITAL,
  escape = VK_ESCAPE,
  space = VK_SPACE,
  page_up = VK_PRIOR,
  page_down = VK_NEXT,
  end = VK_END,
  home = VK_HOME,
  left = VK_LEFT,
  up = VK_UP,
  right = VK_RIGHT,
  down = VK_DOWN,
  print_screen = VK_SNAPSHOT,
  insert = VK_INSERT,
  delete_ = VK_DELETE,
  win = VK_LWIN,
  menu = VK_APPS,
  num_lock = VK_NUMLOCK,
  scroll_lock = VK_SCROLL,

  n0 = '0',
  n1 = '1',
  n2 = '2',
  n3 = '3',
  n4 = '4',
  n5 = '5',
  n6 = '6',
  n7 = '7',
  n8 = '8',
  n9 = '9',

  a = 'A',
  b = 'B',
  c = 'C',
  d = 'D',
  e = 'E',
  f = 'F',
  g = 'G',
  h = 'H',
  i = 'I',
  j = 'J',
  k = 'K',
  l = 'L',
  m = 'M',
  n = 'N',
  o = 'O',
  p = 'P',
  q = 'Q',
  r = 'R',
  s = 'S',
  t = 'T',
  u = 'U',
  v = 'V',
  w = 'W',
  x = 'X',
  y = 'Y',
  z = 'Z',

  f1 = VK_F1,
  f2 = VK_F2,
  f3 = VK_F3,
  f4 = VK_F4,
  f5 = VK_F5,
  f6 = VK_F6,
  f7 = VK_F7,
  f8 = VK_F8,
  f9 = VK_F9,
  f10 = VK_F10,
  f11 = VK_F11,
  f12 = VK_F12,

  hiphen = VK_OEM_MINUS,
  semicolon = VK_OEM_1,
  comma = VK_OEM_COMMA,
  period = VK_OEM_PERIOD,
  slash = VK_OEM_2,
};
}
