#!/usr/bin/env python3
from __future__ import annotations

import argparse
import platform
import shutil
import subprocess
import sys
from pathlib import Path

# ------------------------------------------------------------
# helpers
# ------------------------------------------------------------

def ensure_source_cpp(workspace: Path):
    source_cpp = workspace / "source.cpp"
    if source_cpp.exists():
        return
    template = workspace / "tools" / "templates" / "source.cpp.in"
    if not template.exists():
        raise RuntimeError("source.cpp template not found")
    print("[init_vscode] creating source.cpp from template")
    source_cpp.write_text(template.read_text(encoding="utf-8"), encoding="utf-8")

def ensure_vscode_settings(workspace: Path):
    vscode_dir = workspace / ".vscode"
    vscode_dir.mkdir(parents=True, exist_ok=True)
    settings = vscode_dir / "settings.json"
    if settings.exists():
        return None
    template = workspace / "tools" / "templates" / "settings.json.in"
    if not template.exists():
        raise RuntimeError("settings.json template not found")
    print("[init_vscode] creating .vscode/settings.json from template")
    settings.write_text(template.read_text(encoding="utf-8"), encoding="utf-8")
    return settings

def ensure_cmakelists(workspace: Path):
    cmakelists = workspace / "CMakeLists.txt"
    if cmakelists.exists():
        return
    template = workspace / "tools" / "templates" / "CMakeLists.txt.in"
    if not template.exists():
        raise RuntimeError("CMakeLists.txt template not found")
    print("[init_vscode] creating CMakeLists.txt from template")
    cmakelists.write_text(template.read_text(encoding="utf-8"), encoding="utf-8")

def which_or_error(name: str) -> str:
    p = shutil.which(name)
    if not p:
        raise RuntimeError(f"{name} not found in PATH")
    return p

def pick_mingw_generator() -> str:
    return "Ninja" if shutil.which("ninja") else "MinGW Makefiles"

def run_cmake(root: Path, build: Path, extra: list[str]) -> int:
    cmd = [
        "cmake",
        "-S", str(root),
        "-B", str(build),
        "-DCMAKE_EXPORT_COMPILE_COMMANDS=ON",
        *extra,
    ]
    print("[init_vscode] running:", " ".join(cmd))
    return subprocess.run(cmd).returncode

def collect_headers(root: Path) -> list[Path]:
    if not root.exists():
        return []
    return sorted(p for p in root.rglob("*.h") if p.is_file())

def write_umbrella_header(output_path: Path, header_root: Path, include_prefix: str) -> None:
    headers = collect_headers(header_root)

    lines: list[str] = []
    lines.append("// generated by tools/init.py")
    lines.append("#pragma once")
    lines.append("")

    for header in headers:
        rel = header.relative_to(header_root).as_posix()
        lines.append(f'#include <{include_prefix}/{rel}>')

    lines.append("")
    output_path.write_text("\n".join(lines), encoding="utf-8")

def ensure_umbrella_headers(workspace: Path) -> None:
    yw_root = workspace / "ywlib" / "yw"
    ywx_root = workspace / "ywlib" / "ywx"

    if not yw_root.exists():
        raise RuntimeError(f"yw header root not found: {yw_root}")
    if not ywx_root.exists():
        raise RuntimeError(f"ywx header root not found: {ywx_root}")

    ywlib_header = workspace / "ywlib" / "ywlib"
    ywxlib_header = workspace / "ywlib" / "ywxlib"

    print("[init_vscode] generating umbrella header:", ywlib_header)
    write_umbrella_header(ywlib_header, yw_root, "yw")

    print("[init_vscode] generating umbrella header:", ywxlib_header)
    write_umbrella_header(ywxlib_header, ywx_root, "ywx")

def generate_wrapper_cmakelists(project_root: Path, generated_cmake: Path, kind: str) -> None:
    root_posix = project_root.resolve().as_posix()

    common = f'''cmake_minimum_required(VERSION 3.20)

set(YWLIB_PROJECT_ROOT "{root_posix}")

project(ywlib_wrapper LANGUAGES CXX)

add_subdirectory("${{YWLIB_PROJECT_ROOT}}" "${{CMAKE_BINARY_DIR}}/project_src")

set(YWLIB_OBJECT_TARGET ywlib_object)

if(NOT TARGET ${{YWLIB_OBJECT_TARGET}})
    message(FATAL_ERROR "Expected object target '${{YWLIB_OBJECT_TARGET}}' was not defined by ${{YWLIB_PROJECT_ROOT}}/CMakeLists.txt")
endif()
'''

    if kind == "dll":
        body = r'''
add_library(ywlib_output SHARED $<TARGET_OBJECTS:${YWLIB_OBJECT_TARGET}>)

target_link_libraries(ywlib_output
    PRIVATE
        ${YOUR_APP_LIBRARIES}
)

set(YOUR_DLL_PREFIX "" CACHE STRING "Prefix for DLL/shared library filename")
set(YOUR_DLL_OUTPUT_NAME "${YOUR_APP_NAME}" CACHE STRING "Output filename base for DLL/shared library")

set_target_properties(ywlib_output PROPERTIES
    PREFIX "${YOUR_DLL_PREFIX}"
    OUTPUT_NAME "${YOUR_DLL_OUTPUT_NAME}"
    RUNTIME_OUTPUT_DIRECTORY "${CMAKE_RUNTIME_OUTPUT_DIRECTORY}"
    LIBRARY_OUTPUT_DIRECTORY "${CMAKE_LIBRARY_OUTPUT_DIRECTORY}"
    ARCHIVE_OUTPUT_DIRECTORY "${CMAKE_ARCHIVE_OUTPUT_DIRECTORY}"
)
'''
    elif kind == "exe":
        body = r'''
if (WIN32 AND NOT SHOW_CONSOLE)
    add_executable(ywlib_output WIN32 $<TARGET_OBJECTS:${YWLIB_OBJECT_TARGET}>)
else()
    add_executable(ywlib_output $<TARGET_OBJECTS:${YWLIB_OBJECT_TARGET}>)
endif()

target_link_libraries(ywlib_output
    PRIVATE
        ${YOUR_APP_LIBRARIES}
)

set_target_properties(ywlib_output PROPERTIES
    OUTPUT_NAME "${YOUR_APP_NAME}"
    RUNTIME_OUTPUT_DIRECTORY "${CMAKE_RUNTIME_OUTPUT_DIRECTORY}"
)
'''
    else:
        raise ValueError(f"unknown wrapper kind: {kind}")

    generated_cmake.parent.mkdir(parents=True, exist_ok=True)
    generated_cmake.write_text(common + body, encoding="utf-8")
    print("[init_vscode] generated wrapper cmakelists:", generated_cmake)

# ------------------------------------------------------------
# main
# ------------------------------------------------------------

def main() -> int:
    workspace = Path(__file__).resolve().parents[1]

    ensure_source_cpp(workspace)
    ensure_cmakelists(workspace)
    ensure_umbrella_headers(workspace)

    ap = argparse.ArgumentParser()
    ap.add_argument(
        "--toolchain",
        choices=["gcc", "clang", "msvc", "auto"],
        default="gcc",
        help="Toolchain to use (default: gcc)",
    )
    ap.add_argument("--dll", action="store_true", help="Configure build as DLL")
    ap.add_argument("--build-dir", default="build")
    ap.add_argument("--output-dir", default=None, help="Directory for final binaries (.exe/.dll). Default: same as --build-dir")
    ap.add_argument("--reset-build", action="store_true")
    ap.add_argument("--reset-vscode", action="store_true")
    args = ap.parse_args()

    root = workspace
    build = root / args.build_dir
    output_dir = (root / args.output_dir) if args.output_dir else build
    vscode = root / ".vscode"

    if args.reset_build and build.exists():
        shutil.rmtree(build)
    if args.reset_vscode and vscode.exists():
        shutil.rmtree(vscode)

    build.mkdir(parents=True, exist_ok=True)
    output_dir.mkdir(parents=True, exist_ok=True)

    extra: list[str] = []

    try:
        if args.toolchain == "gcc":
            gen = pick_mingw_generator()
            gpp = which_or_error("g++")
            extra += [
                "-G", gen,
                f"-DCMAKE_CXX_COMPILER={gpp}",
            ]
        elif args.toolchain == "clang":
            clangpp = which_or_error("clang++")
            extra += [
                f"-DCMAKE_CXX_COMPILER={clangpp}",
            ]
        elif args.toolchain == "msvc":
            if platform.system().lower() != "windows":
                raise RuntimeError("msvc toolchain is only valid on Windows")
            extra += ["-G", "Visual Studio 17 2022"]
        elif args.toolchain == "auto":
            pass

    except RuntimeError as e:
        print(
            "[init_vscode] ERROR:", e,
            "\nHint: run from the appropriate environment "
            "(e.g. w64devkit shell for gcc).",
            file=sys.stderr,
        )
        return 2

    out = output_dir.resolve().as_posix()
    extra += [
        f"-DCMAKE_RUNTIME_OUTPUT_DIRECTORY={out}",
        f"-DCMAKE_LIBRARY_OUTPUT_DIRECTORY={out}",
        f"-DCMAKE_ARCHIVE_OUTPUT_DIRECTORY={out}",
    ]

    wrapper_dir = build / ("_dll_src" if args.dll else "_exe_src")
    generate_wrapper_cmakelists(root, wrapper_dir / "CMakeLists.txt", "dll" if args.dll else "exe")

    rc = run_cmake(wrapper_dir, build, extra)
    if rc != 0:
        return rc

    settings = ensure_vscode_settings(root)
    if settings:
        print("[init_vscode] wrote:", settings)

    cc = build / "compile_commands.json"
    if not cc.exists():
        print("[init_vscode] WARNING: compile_commands.json not found.", file=sys.stderr)

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
